server:
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 512Mi

  persistentVolume:
    enabled: true
    existingClaim: prometheus-pvc

alertmanager:
  enabled: false

pushgateway:
  resources:
    requests:
      memory: 64Mi
    limits:
      memory: 128Mi
