Vagrant.configure("2") do |config|
  # Genel ayarlar
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.boot_timeout = 600   # 10 dakika beklesin, yavaş boot'a tolerans

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  NODES = {
    "controlplane"  => { ip: "192.168.56.11", cpus: 2, memory: 4096 },
    "workernode"    => { ip: "192.168.56.21", cpus: 2, memory: 2048 }
  }

  NODES.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name

      node.vm.network "private_network", ip: opts[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.name   = name
        vb.cpus   = opts[:cpus]
        vb.memory = opts[:memory]
      end

      node.vm.provision "shell", inline: <<-SHELL
        set -eux

        apt-get update -y
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release conntrack

        sed -i '/ swap / s/^/#/' /etc/fstab
        swapoff -a

        cat <<EOF | tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

        modprobe br_netfilter

        cat <<EOF | tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF

        sysctl --system

        apt-get install -y containerd
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        systemctl restart containerd
        systemctl enable containerd

        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list


        apt-get update -y
        apt-get install -y kubelet kubeadm kubectl
        apt-mark hold kubelet kubeadm kubectl

        systemctl enable kubelet

        cat <<EOF >> /etc/hosts
192.168.56.11  controlplane1
192.168.56.21  workernode
EOF
      SHELL
    end
  end
end
