adminUser: admin
adminPassword: admin

service:
  type: NodePort
  port: 80
  nodePort: 32000

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi

persistence:
  enabled: true
  existingClaim: grafana-pvc
