apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: cloud-todo
type: Opaque
stringData:   # With stringData, you can provide unencoded values. They will be base64-encoded by Kubernetes.   
  JWT_SECRET: "aSv_lO-dcWuQUQ4OL3BRaWyrfyK27nzzEiTmo9AbMmg" # Created with python -c "import secrets; print(secrets.token_urlsafe(32))" command.
  DB_USER: "cloud-todo"
  DB_PASS: "cloud-todo-pass"
