apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: quay.io/sclorg/postgresql-15-c9s
          ports:
            - containerPort: 5432

          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRESQL_USER

            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRESQL_PASSWORD

            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: POSTGRESQL_DATABASE

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/pgsql/data

      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: todo-db-data
